### ISSUE TITLE
CertEE support broken

### ISSUE THREAD

**Issue by lochiiconnectivity** [chrislee35/passivedns-client#1]
$ pdnstool -e 1.2.3.4
/usr/lib/ruby/1.8/date/format.rb:1055:in `dup': can't dup NilClass (TypeError)
        from /home/foo/pdnstool/client.rb:56:in `join'
        from /home/foo/pdnstool/client.rb:56:in `query'
        from /home/foo/pdnstool/client.rb:55:in `each'
        from /home/foo/pdnstool/client.rb:55:in `query'
        from /home/foo/pdnstool/pdnstool.rb:15:in `pdnslookup'
        from /home/foo/pdnstool/state.rb:64:in `each_query'
        from /home/foo/pdnstool/state.rb:59:in `each'
        from /home/foo/pdnstool/state.rb:59:in `each_query'
        from /home/foo/pdnstool/pdnstool.rb:14:in `pdnslookup'
        from /home/foo/pdnstool/pdnstool.rb:200

$ cat version.rb
module PassiveDNS
  class Client
    VERSION = "1.1.1"
  end
end

**Comment by chrislee35** [comment]
April 2nd and it still isn't up. So I'm removing CERTEE from the list of providers.

**Comment by pinowudi** [comment]
That’s unfortunate. They were a good source of data and will be missed. 

- Drew

**Comment by chrislee35** [comment]
Very true.  CERT-EE is some good people and I'm very sad to see this resource disappear.
