### ISSUE TITLE
Add CIRCL (Luxembourg's CERT) passive DNS database

### ISSUE THREAD

**Issue by elhoim** [chrislee35/passivedns-client#7]
https://www.circl.lu/services/passive-dns/

**Comment by chrislee35** [comment]
I just requested an API key for testing.  While I'm at it, I should probably add PassiveTotal as well.
https://www.passivetotal.org/
I would also like to find someone to write a python version of this tool, possibly leveraging https://github.com/CIRCL/PyPDNS.

**Comment by chrislee35** [comment]
Release 2.0.2 of the passivedns-client drops CERTEE and adds CIRCL and PassiveTotal support.  I need to update the documentation. (I always forget that :)

**Comment by chrislee35** [comment]
Documentation is now updated.  Please review, comment, and close (if you're satisfied).

**Comment by elhoim** [comment]
CIRCL working perfectly so this can be closed.

Thanks!
